alteraColunas_2016 = {'NOTA Matemática Discreta':'Matemática Discreta',
                                 'NOTA Cálculo Diferencial Integral':'Cálculo Diferencial e Integral',
                                 'NOTA Álgebra Linear':'Álgebra Linear',
                                 'NOTA Geometria Analítica':'Geometria Analítica',
                                 'NOTA Análise Combinatória':'Análise Combinatória',
                                 'NOTA Probabilidade e Estatística':'Probabilidade e Estatística',
                                 'NOTA Lógica Matemática':'Lógica Matemática',
                                 'NOTA Organização de Arquivos e Dados':'Organização de Arquivos e Dados',
                                 'NOTA Técnicas de Programação':'Técnicas de Programação',
                                 'NOTA Circuitos Digitais':'Circuitos Digitais',
                                 'NOTA Análise de Algoritmos':'Análise de Algoritmos',
                                 'NOTA Teoria dos Grafos':'Teoria dos Grafos',
                                 'NOTA Linguagens Formais, Autômatos e Computabilidade':'Linguagens Formais, Autômatos e Computabilidade',
                                 'NOTA Algoritmos e Estruturas de Dados':'Algoritmos e Estruturas de Dados',
                                 'NOTA Linguagens de Programação':'Linguagens de Programação',
                                 'NOTA Sistemas Operacionais':'Sistemas Operacionais',
                                 'NOTA Arquitetura e Organização de Computadores':'Arquitetura e Organização de Computadores',
                                 'NOTA Rede de Computadores':'Redes de Computadores',
                                 'NOTA Computação Gráfica':'Computação Gráfica',
                                 'NOTA Inteligência Artificial':'Inteligência Artificial',
                                 'NOTA Engenharia de Software':'Engenharia de Software',
                                 'NOTA Sistemas Distribuídos':'Sistemas Distribuídos',
                                 'NOTA Compiladores':'Compiladores',
                                 'NOTA Processamento de Imagens':'Processamento de Imagens',
                                 'NOTA Banco de Dados':'Banco de Dados'}

alteraColunas_2017 = {'NOTA Matemática Discreta':'Matemática Discreta',
                                 'NOTA Cálculo Diferencial e Integral':'Cálculo Diferencial e Integral',
                                 'NOTA Algebra Linear':'Álgebra Linear',
                                 'NOTA Geometria Analítica':'Geometria Analítica',
                                 'NOTA Análise Combinatória':'Análise Combinatória',
                                 'NOTA Probabilidade e Estatística':'Probabilidade e Estatística',
                                 'NOTA Lógica Matemática':'Lógica Matemática',
                                 'NOTA Organização de Arquivos e Dados':'Organização de Arquivos e Dados',
                                 'NOTA Técnicas de Programação':'Técnicas de Programação',
                                 'NOTA Circuitos Digitais':'Circuitos Digitais',
                                 'NOTA Análise de Algorítmos':'Análise de Algoritmos',
                                 'NOTA Teoria dos Grafos':'Teoria dos Grafos',
                                 'NOTA Linguagens Formais, Autômatos e Computabilidade':'Linguagens Formais, Autômatos e Computabilidade',
                                 'NOTA Algorítmos e Estrutura de Dados':'Algoritmos e Estruturas de Dados',
                                 'NOTA Linguagens de Programação':'Linguagens de Programação',
                                 'NOTA Sistemas Operacionais':'Sistemas Operacionais',
                                 'NOTA Arquitetura e Organização de Computadores':'Arquitetura e Organização de Computadores',
                                 'NOTA Redes de Computadores':'Redes de Computadores',
                                 'NOTA Computação Gráfica':'Computação Gráfica',
                                 'NOTA Inteligência Artificial':'Inteligência Artificial',
                                 'NOTA Engenharia de Software':'Engenharia de Software',
                                 'NOTA Sistemas Distribuídos':'Sistemas Distribuídos',
                                 'NOTA Compiladores':'Compiladores',
                                 'NOTA Processamento de Imagens':'Processamento de Imagens',
                                 'NOTA Banco de Dados':'Banco de Dados'}

alteraColunas_2018 = {'NOTA Matemática Discreta':'Matemática Discreta',
                                 'NOTA Cálculo Diferencial e Integral':'Cálculo Diferencial e Integral',
                                 'NOTA Algebra Linear':'Álgebra Linear',
                                 'NOTA Geometria Analítica':'Geometria Analítica',
                                 'NOTA Analise Combinatória':'Análise Combinatória',
                                 'NOTA Probabilidade e Estatística':'Probabilidade e Estatística',
                                 'NOTA Lógica Matemática':'Lógica Matemática',
                                 'NOTA Organização de Arquivos e Dados':'Organização de Arquivos e Dados',
                                 'NOTA Técnicas de Programação':'Técnicas de Programação',
                                 'NOTA Circuitos Digitais':'Circuitos Digitais',
                                 'NOTA Análise de Algoritmos':'Análise de Algoritmos',
                                 'NOTA Teoria dos Grafos':'Teoria dos Grafos',
                                 'NOTA Linguagens formais, autômatos e Computabilidade':'Linguagens Formais, Autômatos e Computabilidade',
                                 'NOTA Algorítmos e Estrutura de Dados':'Algoritmos e Estruturas de Dados',
                                 'NOTA Linguagens de Programação':'Linguagens de Programação',
                                 'NOTA Sistemas Operacionais':'Sistemas Operacionais',
                                 'NOTA Arquitetura e Organização de Computadores':'Arquitetura e Organização de Computadores',
                                 'NOTA Redes de Computadores':'Redes de Computadores',
                                 'NOTA Computação Gráfica':'Computação Gráfica',
                                 'NOTA Inteligência Artificial':'Inteligência Artificial',
                                 'NOTA Engenharia de Software':'Engenharia de Software',
                                 'NOTA Sistemas Distribuídos':'Sistemas Distribuídos',
                                 'NOTA Compiladores':'Compiladores',
                                 'NOTA Processamento de Imagens':'Processamento de Imagens',
                                 'NOTA Banco de Dados':'Banco de Dados'}

alteraColunas_2019 = {'NOTA Matemática Discreta':'Matemática Discreta',
                                 'NOTA Calculo Diferencial e Integral':'Cálculo Diferencial e Integral',
                                 'NOTA Álgebra Linear':'Álgebra Linear',
                                 'NOTA Geometria Analítica':'Geometria Analítica',
                                 'NOTA Análise Combinatória':'Análise Combinatória',
                                 'NOTA Probabilidade e Estatística':'Probabilidade e Estatística',
                                 'NOTA Lógica Matemática':'Lógica Matemática',
                                 'NOTA Organização de Arquivos e Dados':'Organização de Arquivos e Dados',
                                 'NOTA Técnicas de Programação':'Técnicas de Programação',
                                 'NOTA Circuitos Digitais':'Circuitos Digitais',
                                 'NOTA Análise de Algoritmos':'Análise de Algoritmos',
                                 'NOTA Teoria dos Grafos':'Teoria dos Grafos',
                                 'NOTA Linguagens formais, autômatos e Computabilidade':'Linguagens Formais, Autômatos e Computabilidade',
                                 'NOTA Algoritmos e Estrutura de Dados':'Algoritmos e Estruturas de Dados',
                                 'NOTA Linguagens de Programação':'Linguagens de Programação',
                                 'NOTA Sistemas Operacionais':'Sistemas Operacionais',
                                 'NOTA Arquitetura e Organização de Computadores':'Arquitetura e Organização de Computadores',
                                 'NOTA Redes de Computadores':'Redes de Computadores',
                                 'NOTA Computação Gráfica':'Computação Gráfica',
                                 'NOTA Inteligência Artificial':'Inteligência Artificial',
                                 'NOTA Engenharia de Software':'Engenharia de Software',
                                 'NOTA Sistemas Distribuídos':'Sistemas Distribuídos',
                                 'NOTA Compiladores':'Compiladores',
                                 'NOTA Processamento de Imagens':'Processamento de Imagens',
                                 'NOTA Banco de Dados':'Banco de Dados'}