lista_2016 = ['INSCRICAO',
              'ESPECIALIDADE',
              'PRESENTE DIA1',
              'CARGO',
 'NOTA Matemática Discreta',
 'NOTA Cálculo Diferencial Integral',
 'NOTA Álgebra Linear',
 'NOTA Geometria Analítica',
 'NOTA Análise Combinatória',
 'NOTA Probabilidade e Estatística',
 'NOTA Lógica Matemática',
 'NOTA Organização de Arquivos e Dados',
 'NOTA Técnicas de Programação',
 'NOTA Circuitos Digitais',
 'NOTA Análise de Algoritmos',
 'NOTA Teoria dos Grafos',
 'NOTA Linguagens Formais, Autômatos e Computabilidade',
 'NOTA Algoritmos e Estruturas de Dados',
 'NOTA Linguagens de Programação',
 'NOTA Sistemas Operacionais',
 'NOTA Arquitetura e Organização de Computadores',
 'NOTA Rede de Computadores',
 'NOTA Computação Gráfica',
 'NOTA Inteligência Artificial',
 'NOTA Engenharia de Software',
 'NOTA Sistemas Distribuídos',
 'NOTA Compiladores',
 'NOTA Processamento de Imagens',
 'NOTA Banco de Dados', 'ANO']

lista_2017 = ['INSCRICAO',
              'ESPECIALIDADE',
              'PRESENTE DIA1',
              'CARGO',
 'NOTA Algebra Linear',
 'NOTA Análise Combinatória',
 'NOTA Cálculo Diferencial e Integral',
 'NOTA Geometria Analítica',
 'NOTA Matemática Discreta',
 'NOTA Probabilidade e Estatística',
 'NOTA Lógica Matemática',
 'NOTA Análise de Algorítmos',
 'NOTA Algorítmos e Estrutura de Dados',
 'NOTA Arquitetura e Organização de Computadores',
 'NOTA Circuitos Digitais',
 'NOTA Linguagens de Programação',
 'NOTA Linguagens Formais, Autômatos e Computabilidade',
 'NOTA Organização de Arquivos e Dados',
 'NOTA Sistemas Operacionais',
 'NOTA Técnicas de Programação',
 'NOTA Teoria dos Grafos',
 'NOTA Banco de Dados',
 'NOTA Compiladores',
 'NOTA Computação Gráfica',
 'NOTA Engenharia de Software',
 'NOTA Inteligência Artificial',
 'NOTA Processamento de Imagens',
 'NOTA Redes de Computadores',
 'NOTA Sistemas Distribuídos', 'ANO']

lista_2018 = ['INSCRICAO',
              'ESPECIALIDADE',
              'PRESENTE DIA1',
              'CARGO',
 'NOTA Algebra Linear',
 'NOTA Analise Combinatória',
 'NOTA Cálculo Diferencial e Integral',
 'NOTA Geometria Analítica',
 'NOTA Matemática Discreta',
 'NOTA Probabilidade e Estatística',
 'NOTA Lógica Matemática',
 'NOTA Análise de Algoritmos',
 'NOTA Algorítmos e Estrutura de Dados',
 'NOTA Arquitetura e Organização de Computadores',
 'NOTA Circuitos Digitais',
 'NOTA Linguagens de Programação',
 'NOTA Linguagens formais, autômatos e Computabilidade',
 'NOTA Organização de Arquivos e Dados',
 'NOTA Sistemas Operacionais',
 'NOTA Técnicas de Programação',
 'NOTA Teoria dos Grafos',
 'NOTA Banco de Dados',
 'NOTA Compiladores',
 'NOTA Computação Gráfica',
 'NOTA Engenharia de Software',
 'NOTA Inteligência Artificial',
 'NOTA Processamento de Imagens',
 'NOTA Redes de Computadores','NOTA Sistemas Distribuídos', 'ANO']

lista_2019 = ['INSCRICAO',
              'ESPECIALIDADE',
              'PRESENTE DIA1',
              'CARGO',
 'NOTA Álgebra Linear',
 'NOTA Análise Combinatória',
 'NOTA Calculo Diferencial e Integral',
 'NOTA Geometria Analítica',
 'NOTA Matemática Discreta',
 'NOTA Probabilidade e Estatística',
 'NOTA Lógica Matemática',
 'NOTA Análise de Algoritmos',
 'NOTA Algoritmos e Estrutura de Dados',
 'NOTA Arquitetura e Organização de Computadores',
 'NOTA Circuitos Digitais',
 'NOTA Linguagens de Programação',
 'NOTA Linguagens formais, autômatos e Computabilidade',
 'NOTA Organização de Arquivos e Dados',
 'NOTA Sistemas Operacionais',
 'NOTA Técnicas de Programação',
 'NOTA Teoria dos Grafos',
 'NOTA Banco de Dados',
 'NOTA Compiladores',
 'NOTA Computação Gráfica',
 'NOTA Engenharia de Software','NOTA Inteligência Artificial',
 'NOTA Processamento de Imagens',
 'NOTA Redes de Computadores',
 'NOTA Sistemas Distribuídos', 'ANO']

